blank_issues_enabled: false
contact_links:
  - name: '💬 Support: Discussions'
    url: https://github.com/udecode/jotai-x/discussions
    about: Share ideas, ask and answer questions in our Discussions.
